### ISSUE TITLE
Seems like the link to JSONview doesn't work anymore

### ISSUE THREAD

**Issue by BrunoBoehm** [learn-co-curriculum/apis-and-postman#7]
Is this better to use https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa?hl=en then ?

**Comment by itzsaga** [comment]
The link worked for me.

**Comment by gj** [comment]
HI @BrunoBoehm !

JSONView was updated on 1/6/17. Should be all good now. Thanks!
